### ISSUE TITLE
App in background sound disappears

### ISSUE THREAD

**Issue by Frekansapp** [zxcpoiu/react-native-incall-manager#105]
After a while the connection is disconnecting while the application is in the background. I'm testing on Android how can i prevent disconnect problem

**Comment by zxcpoiu** [comment]
This is the nature of react-native, and mobile platform tends to not allow app to do tasks in the background these days. ( you only have short period of time )

On android, there are several ways, like wake lock, connection service...etc depends on the type of your app. On iOS, you can try call-kit to handle your phone call.

Since this is out of scope of this lib, I am closing it now.

**Comment by Frekansapp** [comment]
Can you please checkout this discussion [`React native discourse group`](https://react-native-webrtc.discourse.group/t/app-in-background-sound-disappears/43?u=eren). I trying to solve this problem for days. Looks like nobody cares except me.

**Comment by Frekansapp** [comment]
> 
> 
> This is the nature of react-native, and mobile platform tends to not allow app to do tasks in the background these days. ( you only have short period of time )
> 
> On android, there are several ways, like wake lock, connection service...etc depends on the type of your app. On iOS, you can try call-kit to handle your phone call.
> 
> Since this is out of scope of this lib, I am closing it now.

Can you please checkout this discussion [`React native discourse group`](https://react-native-webrtc.discourse.group/t/app-in-background-sound-disappears/43?u=eren). I trying to solve this problem for days. Looks like nobody cares except me.
