### ISSUE TITLE
InCallManager.stop() doesn't mute

### ISSUE THREAD

**Issue by szymonzmyslony** [zxcpoiu/react-native-incall-manager#18]
I'm trying to mute current session using InCallManager.stop(); however, it deosn't mute the session. Can it be connected with the fact that I also use WebRTC?

**Comment by zxcpoiu** [comment]
I assumed your question is related to https://github.com/oney/react-native-webrtc/issues/179

InCallManager start() stop() means should start/stop functions to control audio route and audio type. it doesn't mean to mute/unmute a audio session.

webrtc controls audio session and has it's own audio player, this module mainly override the preferred audio stream type ( ring/call/speaker/earpiece...etc ) rather than controls webrtc audio player directly.

I'm going to close this, because it more like a webrtc issue.
fell free to continue it on https://github.com/oney/react-native-webrtc/issues/179
