### ISSUE TITLE
turnScreenOn not working

### ISSUE THREAD

**Issue by zoharlevin** [zxcpoiu/react-native-incall-manager#27]
maybe i'm missing something..  but calling `InCallManager.turnScreenOn()` doesn't seem to actually do anything

i'm on these versions:
"react-native-incall-manager": "2.1.0",
"react-native": "0.42.0-rc.3",

**Comment by zxcpoiu** [comment]
oh, sorry for the bad naming.

`turnScreenOn` is not a real `turnScreenOn` :(
it meant to be invoke during a phone call screen ( which means the phone is unlocked )
and turn on/off based on call status, like if user is using earpiece, it will invoke `turnScreenOff` something like that.

if you want to `wake` phone to turn screen on while an incoming call received, you might need the following:

* acquire wake lock
* bypass keyguard
* set keep screen on

....etc

but it's a bit tricky since different android version and manufacturer has different policies toward `wake up phone` action... , you need to experiment on your major target devices.

**Comment by zxcpoiu** [comment]
You can check how this library invoke locks in `InCallWakeLockUtils` in the latest master.
closing this now.
