### ISSUE TITLE
Not using speakerphone for video call

### ISSUE THREAD

**Issue by bsiddiqui** [zxcpoiu/react-native-incall-manager#40]
On my iPhone 6 I've started the call with `InCallManager.start({ media: 'video' })` but it uses the earpiece. On an iPhone 7 it correctly uses the speakerphone, though

**Comment by JLLLinn** [comment]
The issue happens to me when I have earphones plugged in before calling start({media:'video'}), that way once I unplug the earphone it will route through the receiver instead of the speaker.

Maybe using DefaultToSpeaker when setting the category in the code would work but that involve changing the native code.

**Comment by zxcpoiu** [comment]
thanks for reporting.
seems these two issues are slightly different.

@JLLLinn might related to [updateAudioRoute](https://github.com/zxcpoiu/react-native-incall-manager/blob/master/ios/RNInCallManager/RNInCallManager.swift#L145) and 
[oldDeviceUnavailable](https://github.com/zxcpoiu/react-native-incall-manager/blob/master/ios/RNInCallManager/RNInCallManager.swift#L414)
no clues on @bsiddiqui 's issue currently.

I mainly test it on audio mode since I don't have video scenario now. And have a limited time to debug video part :(

if you guys can send a PR for more proper way the video should be, I am happy to merge it. :)

**Comment by Jerameel** [comment]
I'm also experiencing this problem. I used media as video to prevent proximity sensors from turning off the screen. This workaround is all well with android, however iOS doesnt seem to work with it.

**Comment by bsiddiqui** [comment]
@zxcpoiu I've noticed a really odd behavior: I get audio out of the earpiece if the user has just installed the app and given camera/mic permissions. If I kill the app and then try and join a webrtc session again, it properly plays through the speaker. Does iOS setup audio sessions differently if the app boots with camera/mic permissions than if it doesn't? I've been researching for a while and haven't found much.

**Comment by zxcpoiu** [comment]
@bsiddiqui

I've encountered similar issue but different.
ios behavior strangely like we can not control lots of actions of this lib when user initially installed app.
until user quit and restart app, everything goes back to normal.

But unfortunately, I don't have any clues neither currently. :(

**Comment by kristiansorens** [comment]
Just posted a workaround in #49
