### ISSUE TITLE
demo screen ?

### ISSUE THREAD

**Issue by smolleyes** [zxcpoiu/react-native-incall-manager#47]
hi

anyone has a basic screen to provide as exemple ? 

thanks

**Comment by zxcpoiu** [comment]
@smolleyes 

do you mean screen shot?

this library is a pure plugin mostly to work with `react-native-webrtc`
there is no screenshot since `react-native-incall-manager` doesn't implement any view stuff.

and `react-native-webrtc` is a library as well, provides `peer connection` api similar to browser.
`react-native-webrtc` has a view which simply render video streams from your camera or remote media.

if you would like to see a demo, I think jitsi-meet mobile version is a good one. :)
