### ISSUE TITLE
Ring doesn't repeat

### ISSUE THREAD

**Issue by bsiddiqui** [zxcpoiu/react-native-incall-manager#52]
When I call `InCallManager.start({ media: 'audio', ringback: '_DEFAULT_ })` I hear the ringback play once but then it doesn't repeat

**Comment by zxcpoiu** [comment]
I don't encounter this issue though.
audio may be overridden by another process/app or InCallManager stopped caused by your app logic or some errors internally.
 
you can firstly remove all unnecessary code, said, a brand new project, then just invoke a single line of  `InCallManager.start({ media: 'audio', ringback: '_DEFAULT_ })` to check where the problem is

**Comment by bsiddiqui** [comment]
Ah figured it out - I'm using [`react-native-callkit`](https://github.com/ianlin/react-native-callkit) and the startCall function interrupts the audio process. 

I was able to fix it by waiting to call `.start()` until the `react-native-callkit` `didActivateAudioSession` fires.

**Comment by bsiddiqui** [comment]
@zxcpoiu do you have any idea why the call my ring the first time I call and then subsequent attempts don't ring?

**Comment by zxcpoiu** [comment]
@bsiddiqui thanks for sharing that :+1: 

it is the same way to debug, you can start a brand new project, and `start()` -> `stop()` -> `start()` to see if it also rings at the second time.

maybe you did not `stop()` properly so inCallManager considers it has been already started?
you can check https://github.com/zxcpoiu/react-native-incall-manager/issues/38#issuecomment-320966363 as a example to make sure deactivate/reset all your `In Call` stuff / vars properly.
