### ISSUE TITLE
how to dismiss lockscreen when receiving calls

### ISSUE THREAD

**Issue by dev-hamid** [zxcpoiu/react-native-incall-manager#74]
right now i have an incoming call component i want it to appear apove the lock screen any idea how?

**Comment by zxcpoiu** [comment]
You might want to take a look at:

* KeyguardManager
* PowerManager

And maybe acquired a FullWakeLock while receiving call and release it after then.

There are some internal utils in https://github.com/zxcpoiu/react-native-incall-manager/blob/master/android/src/main/java/com/zxcpoiu/incallmanager/InCallWakeLockUtils.java
that you might interested in.

Closing this since this is out of scope of this module. StackOverflow should be a better place to get this kind of help.
